# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk.xci
# IP: The module: 'clk_2_pclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk.xci
# IP: The module: 'clk_2_pclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VHDL/zybo/vga_zybo/vga_zybo.srcs/sources_1/ip/clk_2_pclk/clk_2_pclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_2_pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
